### PR TITLE
PIN pad reader support

### PR DESCRIPTION
**Pull request by dirkx**
PIN pad reader support and minor cleanup labels.

### CODE REVIEW

**Comment by martinpaljak** [comment]
Okay, how do we clean this up and see what's the essence inside ?

**Comment by frankmorgner** [comment]
This PR is useless in its current state. Also, the only interesting commit seems to be 36297ae2240c1a8a5be7a26141ac33b17428e9d5 which also only solves a minor corner case. In effect, I think this PR can be closed.

**Comment by dirkx** [comment]
> On 24 Nov 2015, at 23:29, Frank Morgner <notifications@github.com> wrote:
> 
> This PR is useless in its current state. Also, the only interesting commit seems to be 36297ae which also only solves a minor corner case. In effect, I think this PR can be closed.
> 
https://github.com/dirkx/OpenSC.tokend/commit/36297ae2240c1a8a5be7a26141ac33b17428e9d5

That is the crux of the matter. I am not sure it is a corner case - it is getting really rather common in the medical space in Europe to use readers with a PIN keypad. (eg simple  - like a SPR532 and many (medical) pos style terminals with a screen and keyboard).

Currently these cannot be used - as the popup will return a 

	pin =(char *)“”; pin_length=0;

which does NOT trigger the defering to the PIN keypad on the reader; For that pin = NULL is needed. (You can argue that the bug is not on this side; but on the side of the desktop PIN capture).

So this patch *makes it possible* to use a PIN reader.

So I am not sure it is a corner case.

Dw


*: There is another aspect - for compliance reasons it is desirable to ‘force’ the use of a PIN keypad on the reader; For those you could argue that something like

+  if (mScP15Card->card->reader->capabilities & SC_READER_CAP_PIN_PAD) {
+               if (getenv(“XXX_MANDATORY_PINREADERUSE”)) {
+                       sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL, “Force PIN entry to the reader keypad.");
+                       pin = NULL;
+               } else 
+               if (pinLength == 0) {
+                       sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL, "Defer PIN entry to the reader keypad.");
+                       pin = NULL;
+               } else {
+                       // We are not block key entry from the keypad. As it is too late at
+                       // this point; such should really be done by advertizing the right
+                       // data in getAcl to the operating system.
+                       //
+                       sc_debug(mScCtx, SC_LOG_DEBUG_NORMAL, "Warning: the reader keypad is not used; PIN entered on keyboard.");
+               }
+       };

**Comment by frankmorgner** [comment]
I think the correct (tm) fix would be to avoid the PIN prompt entirely by announcing a "protected" PIN (read: a PIN that's always prompted at the reader).

**Comment by dirkx** [comment]
On 25 Nov 2015, at 13:49, Frank Morgner <notifications@github.com> wrote:

> I think the correct (tm) fix would be to avoid the PIN prompt entirely by announcing a "protected" PIN (read: a PIN that's always prompted at the reader).

I am not sure the API allows for this - though agreed - in a perfect world we would pick up the PIN on the reader only policy from the reader. 

This is compounded in general by two practical issues; a fair number of readers misimplements its ability; and it is not uncommon for situations to have just 0-9 on the PIN pad of the reader; and a card which can for some transactions also uses alpha chars.

So the current approach is to take a ‘non-entry’ as a ‘defer’ at that API.

Dw.

**Comment by frankmorgner** [comment]
For some time now, I tried registering a `ProtectedPWSubject` (`CSSM_ACL_SUBJECT_TYPE_PROTECTED_PASSWORD`) instead of a `PromptPWSubject`. From the few bits of documentation in the code this seems to be the way of properly announcing a PIN that's validated via PIN pad. However, I did not get this to work, which makes your workaround the only usable solution at the moment. Could you make a new PR that only includes dirkx@36297ae?

**Comment by dirkx** [comment]
On 25 Nov 2015, at 14:46, Frank Morgner <notifications@github.com> wrote:

> For some time now, I tried registering a ProtectedPWSubject (CSSM_ACL_SUBJECT_TYPE_PROTECTED_PASSWORD) instead of a PromptPWSubject. From the few bits of documentation in the code this seems to be the way of properly announcing a PIN that's validated via PIN pad.

Agreed; that is the proper approach. But I know of only one HW/software combination where that actually works end to end (via Apple its tokend).

> However, I did not get this to work, which makes your workaround the only usable solution at the moment. Could you make a new PR that only includes dirkx@36297ae <https://github.com/dirkx/OpenSC.tokend/commit/36297ae>?

Will do.

Dw.

**Comment by dirkx** [comment]
> On 25 Nov 2015, at 15:38, Dirk-Willem van Gulik <dirkx@webweaving.org> wrote:
> 
> On 25 Nov 2015, at 14:46, Frank Morgner <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
>> For some time now, I tried registering a ProtectedPWSubject (CSSM_ACL_SUBJECT_TYPE_PROTECTED_PASSWORD) instead of a PromptPWSubject. From the few bits of documentation in the code this seems to be the way of properly announcing a PIN that's validated via PIN pad.
> 
> Agreed; that is the proper approach. But I know of only one HW/software combination where that actually works end to end (via Apple its tokend).
> 
>> However, I did not get this to work, which makes your workaround the only usable solution at the moment. Could you make a new PR that only includes dirkx@36297ae <https://github.com/dirkx/OpenSC.tokend/commit/36297ae>?
> 
> Will do.

PR #19.

Dw.

**Comment by martinpaljak** [comment]
AFAIK there is no way to get a PIN entry dialog (and ever will, given that the Tokend is destined for extinction in favor of the CryptoTokenKit thing). The workaround is even more important for readers such as the Gemalto C700 pinpad that *forbids* PIN entry from the host.

**Pull request closed without merging**
