### PR TITLE
Use dedicated Xcode variable for deploy target

### PR DESCRIPTION
**Pull request by metsma**
Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by frankmorgner** [comment]
I'm not used to Xcode. What does a dedicated variable change/improve?

**Comment by metsma** [comment]
Shows in project view that target is set 10.9 https://dl.dropboxusercontent.com/u/59091211/Screen%20Shot%202015-11-26%20at%2022.30.59.png
 also other resources (eg. xib) can understand deploy target

**Comment by frankmorgner** [comment]
did you verify that it also sets `-mmacosx-version-min`?

**Comment by metsma** [comment]
man clang

       MACOSX_DEPLOYMENT_TARGET
           If -mmacosx-version-min is unspecified, the default deployment target is read from this environment
           variable.  This option only affects darwin targets.

**Comment by frankmorgner** [comment]
ok, thanks

**Pull request merged**
