### PR TITLE
Fixes build and installation on OS X 10.11

### PR DESCRIPTION
**Pull request by frankmorgner**

### CODE REVIEW

**Comment by frankmorgner** [comment]
@martinpaljak any objections merging this PR?

**Comment by frankmorgner** [comment]
I implemented `pinStatus()`. However, I'm not sure if it will have any impact. During my tests this function was never called by the upper layer anyway...

**Comment by martinpaljak** [comment]
I'll have a look at all the OSX code in the light of 10.11 (read: boot the still not-default parition and try compiling-using everything) before the end of this week.

The pin status IIRC was never really obvious and last time I checked, had no relation other than "ui sugar" for some  situations that had a single global PIN (thus a possible global "unlocked" state)

**Comment by metsma** [comment]
Why not keep the support older OSX versions?
-mmacosx-version-min=10.9 forces to min osx version

**Comment by martinpaljak** [comment]
SDK and minimal OSX version must not be in sync

**Comment by metsma** [comment]
SDKROOT = macosx;
This points to latest SDK

**Comment by frankmorgner** [comment]
I hope to get additional confirmation about the PIN issue from @mouse07410

**Comment by frankmorgner** [comment]
Apple's support for 10.8 will soon drop, see http://www.computerworld.com/article/2950580/operating-systems/the-end-is-near-for-os-x-mountain-lion-support.html. 10.9 differs significantly in it PC/SC layer, there is no reason to officially support older versions.

You may compile with different flags yourself and it will still work on older versions...

**Comment by frankmorgner** [comment]
got confirmation from @mouse07410 in https://github.com/OpenSC/OpenSC/issues/570

**Comment by metsma** [comment]
"10.9 differs significantly in its PC/SC layer" compared with 10.10 or ...?

**Comment by frankmorgner** [comment]
@metsma yes, with 10.10 apple decided to implement its own PC/SC framework with all the fun of a number of new bugs...

**Comment by frankmorgner** [comment]
see http://ludovicrousseau.blogspot.de/2015/10/os-x-el-capitan-and-smart-cards-status.html

**Comment by metsma** [comment]
I know this info but don't understand what you mean with "10.9 differs significantly in its PC/SC layer, there is no reason to officially support older versions."
10.9 pcsc layer is same as 10.8

**Comment by frankmorgner** [comment]
See https://github.com/OpenSC/OpenSC/issues/480 and https://github.com/OpenSC/OpenSC/pull/516

**Comment by metsma** [comment]
then you should change the minimum to 10.10 then???

**Comment by frankmorgner** [comment]
Well... it *is* set so for the OpenSC bundle. Why the tokend needs 10.9, I don't know. This restriction has already been there earlier.

**Comment by mouse07410** [comment]
I don't think OpenSC.tokend still needs 10.9.

Sent from my iPad

On Nov 11, 2015, at 06:37, Frank Morgner <notifications@github.com<mailto:notifications@github.com>> wrote:


Well... it is set so for the OpenSC bundle. Why the tokend needs 10.9, I don't know. This restriction has already been there earlier.

**Comment by frankmorgner** [comment]
@martinpaljak do you have any updates yet?

@martinpaljak by the way, what was the reason to include all the system headers in OpenSC.tokend? Apple's smartcardservices don't need to ship them...

**Comment by frankmorgner** [comment]
@martinpaljak want to add me as contributor so that I can merge/handle the tokend part, too?

**Comment by frankmorgner** [comment]
@martinpaljak ... with write access, please ;-)

**Comment by LudovicRousseau** [comment]
@frankmorgner you now have write access.
https://github.com/OpenSC/OpenSC.tokend/settings/collaboration

**Comment by frankmorgner** [comment]
thanks

**Pull request merged**
